---
- name: Converge
  hosts: all
  tasks:
    - name: print out os family
      debug: msg={{ ansible_os_family }}
    - name: Include ansible-role-ohmy
      include_role:
        name: ansible-role-ohmy
